/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaleRouteRouteImport } from './routes/$locale/route'
import { Route as LocaleAdminRouteImport } from './routes/$locale/_admin'
import { Route as LocaleAuthRouteImport } from './routes/$locale/_auth'
import { Route as LocaleDashboardRouteImport } from './routes/$locale/_dashboard'
import { Route as LocalePublicRouteImport } from './routes/$locale/_public'
import { Route as LocaleAuthForgotPasswordRouteImport } from './routes/$locale/_auth/forgot-password'
import { Route as LocaleAuthLoginRouteImport } from './routes/$locale/_auth/login'
import { Route as LocaleAuthRegisterRouteImport } from './routes/$locale/_auth/register'
import { Route as LocalePublicIndexRouteImport } from './routes/$locale/_public/index'
import { Route as LocaleAdminAdminIndexRouteImport } from './routes/$locale/_admin/admin/index'
import { Route as LocaleDashboardDashboardIndexRouteImport } from './routes/$locale/_dashboard/dashboard/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleRouteRoute = LocaleRouteRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleAdminRoute = LocaleAdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleAuthRoute = LocaleAuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleDashboardRoute = LocaleDashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocalePublicRoute = LocalePublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleAuthForgotPasswordRoute =
  LocaleAuthForgotPasswordRouteImport.update({
    id: '/forgot-password',
    path: '/forgot-password',
    getParentRoute: () => LocaleAuthRoute,
  } as any)
const LocaleAuthLoginRoute = LocaleAuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => LocaleAuthRoute,
} as any)
const LocaleAuthRegisterRoute = LocaleAuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => LocaleAuthRoute,
} as any)
const LocalePublicIndexRoute = LocalePublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocalePublicRoute,
} as any)
const LocaleAdminAdminIndexRoute = LocaleAdminAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => LocaleAdminRoute,
} as any)
const LocaleDashboardDashboardIndexRoute =
  LocaleDashboardDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => LocaleDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteRouteWithChildren
  '/$locale/forgot-password': typeof LocaleAuthForgotPasswordRoute
  '/$locale/login': typeof LocaleAuthLoginRoute
  '/$locale/register': typeof LocaleAuthRegisterRoute
  '/$locale/': typeof LocalePublicIndexRoute
  '/$locale/admin/': typeof LocaleAdminAdminIndexRoute
  '/$locale/dashboard/': typeof LocaleDashboardDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$locale': typeof LocalePublicIndexRoute
  '/$locale/forgot-password': typeof LocaleAuthForgotPasswordRoute
  '/$locale/login': typeof LocaleAuthLoginRoute
  '/$locale/register': typeof LocaleAuthRegisterRoute
  '/$locale/admin': typeof LocaleAdminAdminIndexRoute
  '/$locale/dashboard': typeof LocaleDashboardDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteRouteWithChildren
  '/$locale/_admin': typeof LocaleAdminRouteWithChildren
  '/$locale/_auth': typeof LocaleAuthRouteWithChildren
  '/$locale/_dashboard': typeof LocaleDashboardRouteWithChildren
  '/$locale/_public': typeof LocalePublicRouteWithChildren
  '/$locale/_auth/forgot-password': typeof LocaleAuthForgotPasswordRoute
  '/$locale/_auth/login': typeof LocaleAuthLoginRoute
  '/$locale/_auth/register': typeof LocaleAuthRegisterRoute
  '/$locale/_public/': typeof LocalePublicIndexRoute
  '/$locale/_admin/admin/': typeof LocaleAdminAdminIndexRoute
  '/$locale/_dashboard/dashboard/': typeof LocaleDashboardDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/$locale/forgot-password'
    | '/$locale/login'
    | '/$locale/register'
    | '/$locale/'
    | '/$locale/admin/'
    | '/$locale/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$locale'
    | '/$locale/forgot-password'
    | '/$locale/login'
    | '/$locale/register'
    | '/$locale/admin'
    | '/$locale/dashboard'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/$locale/_admin'
    | '/$locale/_auth'
    | '/$locale/_dashboard'
    | '/$locale/_public'
    | '/$locale/_auth/forgot-password'
    | '/$locale/_auth/login'
    | '/$locale/_auth/register'
    | '/$locale/_public/'
    | '/$locale/_admin/admin/'
    | '/$locale/_dashboard/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRouteRoute: typeof LocaleRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/_admin': {
      id: '/$locale/_admin'
      path: ''
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleAdminRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/_auth': {
      id: '/$locale/_auth'
      path: ''
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleAuthRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/_dashboard': {
      id: '/$locale/_dashboard'
      path: ''
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleDashboardRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/_public': {
      id: '/$locale/_public'
      path: ''
      fullPath: '/$locale'
      preLoaderRoute: typeof LocalePublicRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/_auth/forgot-password': {
      id: '/$locale/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/$locale/forgot-password'
      preLoaderRoute: typeof LocaleAuthForgotPasswordRouteImport
      parentRoute: typeof LocaleAuthRoute
    }
    '/$locale/_auth/login': {
      id: '/$locale/_auth/login'
      path: '/login'
      fullPath: '/$locale/login'
      preLoaderRoute: typeof LocaleAuthLoginRouteImport
      parentRoute: typeof LocaleAuthRoute
    }
    '/$locale/_auth/register': {
      id: '/$locale/_auth/register'
      path: '/register'
      fullPath: '/$locale/register'
      preLoaderRoute: typeof LocaleAuthRegisterRouteImport
      parentRoute: typeof LocaleAuthRoute
    }
    '/$locale/_public/': {
      id: '/$locale/_public/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocalePublicIndexRouteImport
      parentRoute: typeof LocalePublicRoute
    }
    '/$locale/_admin/admin/': {
      id: '/$locale/_admin/admin/'
      path: '/admin'
      fullPath: '/$locale/admin/'
      preLoaderRoute: typeof LocaleAdminAdminIndexRouteImport
      parentRoute: typeof LocaleAdminRoute
    }
    '/$locale/_dashboard/dashboard/': {
      id: '/$locale/_dashboard/dashboard/'
      path: '/dashboard'
      fullPath: '/$locale/dashboard/'
      preLoaderRoute: typeof LocaleDashboardDashboardIndexRouteImport
      parentRoute: typeof LocaleDashboardRoute
    }
  }
}

interface LocaleAdminRouteChildren {
  LocaleAdminAdminIndexRoute: typeof LocaleAdminAdminIndexRoute
}

const LocaleAdminRouteChildren: LocaleAdminRouteChildren = {
  LocaleAdminAdminIndexRoute: LocaleAdminAdminIndexRoute,
}

const LocaleAdminRouteWithChildren = LocaleAdminRoute._addFileChildren(
  LocaleAdminRouteChildren,
)

interface LocaleAuthRouteChildren {
  LocaleAuthForgotPasswordRoute: typeof LocaleAuthForgotPasswordRoute
  LocaleAuthLoginRoute: typeof LocaleAuthLoginRoute
  LocaleAuthRegisterRoute: typeof LocaleAuthRegisterRoute
}

const LocaleAuthRouteChildren: LocaleAuthRouteChildren = {
  LocaleAuthForgotPasswordRoute: LocaleAuthForgotPasswordRoute,
  LocaleAuthLoginRoute: LocaleAuthLoginRoute,
  LocaleAuthRegisterRoute: LocaleAuthRegisterRoute,
}

const LocaleAuthRouteWithChildren = LocaleAuthRoute._addFileChildren(
  LocaleAuthRouteChildren,
)

interface LocaleDashboardRouteChildren {
  LocaleDashboardDashboardIndexRoute: typeof LocaleDashboardDashboardIndexRoute
}

const LocaleDashboardRouteChildren: LocaleDashboardRouteChildren = {
  LocaleDashboardDashboardIndexRoute: LocaleDashboardDashboardIndexRoute,
}

const LocaleDashboardRouteWithChildren = LocaleDashboardRoute._addFileChildren(
  LocaleDashboardRouteChildren,
)

interface LocalePublicRouteChildren {
  LocalePublicIndexRoute: typeof LocalePublicIndexRoute
}

const LocalePublicRouteChildren: LocalePublicRouteChildren = {
  LocalePublicIndexRoute: LocalePublicIndexRoute,
}

const LocalePublicRouteWithChildren = LocalePublicRoute._addFileChildren(
  LocalePublicRouteChildren,
)

interface LocaleRouteRouteChildren {
  LocaleAdminRoute: typeof LocaleAdminRouteWithChildren
  LocaleAuthRoute: typeof LocaleAuthRouteWithChildren
  LocaleDashboardRoute: typeof LocaleDashboardRouteWithChildren
  LocalePublicRoute: typeof LocalePublicRouteWithChildren
}

const LocaleRouteRouteChildren: LocaleRouteRouteChildren = {
  LocaleAdminRoute: LocaleAdminRouteWithChildren,
  LocaleAuthRoute: LocaleAuthRouteWithChildren,
  LocaleDashboardRoute: LocaleDashboardRouteWithChildren,
  LocalePublicRoute: LocalePublicRouteWithChildren,
}

const LocaleRouteRouteWithChildren = LocaleRouteRoute._addFileChildren(
  LocaleRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRouteRoute: LocaleRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
